### PR TITLE
Add aicsimageio version pin

### PR DESCRIPTION
**Pull request by evamaxfield**
In preparation for aicsimageio 3.0.0

### CODE REVIEW

**Review by AetherUnbound — APPROVED** [review]
Is this package really this many versions behind? Wild 🚀

**Comment by donovanr** [comment]
didn't we pin to this version because of a weird tifffile bug? i remember jackson and matt and I figuring out that only one specific subversion of aicsimage would work.  does the update resolve that problem?

**Comment by JacksonMaxfield** [comment]
> didn't we pin to this version because of a weird tifffile bug? i remember jackson and matt and I figuring out that only one specific subversion of aicsimage would work. does the update resolve that problem?

@donovanr Even `aicsimageio` 3.0.0 pins `tifffile` to the "safe" version, but this change is because `aicsimageio` 3.0.0 is a rather drastic but much welcome change set to the core functionality of the package.

**Review by donovanr — APPROVED** [review]
ok

**Pull request merged**
